version: '3.8'

services:
    dev:
        container_name: homelab-pi-discord-bot
        image: punparin/homelab-pi-discord-bot:local
        env_file:
            - .env
        volumes:
            - ./config.json:/app/config.json
            - ./id_rsa:/app/id_rsa
        ports:
            - 3000:3000
        restart: unless-stopped